backend:
  name: github
  repo: YOUR_GH_USERNAME/YOUR_REPO_NAME # TODO: Please update this
  branch: main
  auth_endpoint: /api/auth

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }